server:
  port: 80
  tomcat:
    uri-encoding: utf-8
#Spring
spring:
  messages:
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  mail:
    host: smtp.163.com
    username: zs15991670773@163.com
    password: herocandy521
    default-encoding: utf-8
    port: 25
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
prop:
  upload-folder: files/
mail:
  fromMail.addr: zs15991670773@163.com
# MyBatis
mybatis:
    typeAliasesPackage: cn.xupt.reward
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    configLocation: classpath:mybatis/mybatis-config.xml
# PageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#redis
redis:
    host: localhost
    port: 6379
    password: root
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEbabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
#mail
